import PDFDocument from "pdfkit";

import type { CertificateType } from "@/types/domain";

export type PdfReportInput = {
  title: string;
  subtitle: string;
  lines: string[];
};

export function createSimplePdfReport(input: PdfReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).text(input.title, { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#475569").text(input.subtitle);
    doc.moveDown(1.5);
    doc.fillColor("#0f172a").fontSize(11);

    input.lines.forEach((line) => {
      doc.text(line, { lineGap: 5 });
    });

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor("#64748b")
      .text(
        "Generated by ORATRACK. Verify all values before official submission.",
      );
    doc.end();
  });
}

export type CertificatePdfInput = {
  certificateType: CertificateType;
  learnerName: string;
  lrn: string;
  schoolYearName: string;
  gradeLevelLabel: string;
  sectionName: string;
  templateName?: string;
  templateImage?: Buffer;
  generatedAt: string;
};

export function createCertificatePdf(
  input: CertificatePdfInput,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      layout: "landscape",
      margin: 48,
      size: "A4",
    });
    const chunks: Buffer[] = [];
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const title =
      input.certificateType === "completion"
        ? "Certificate of Completion"
        : "Certificate of Recognition";

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    if (input.templateImage) {
      doc.image(input.templateImage, 36, 36, {
        align: "center",
        fit: [pageWidth - 72, pageHeight - 72],
        valign: "center",
      });
      doc
        .save()
        .opacity(0.86)
        .fillColor("#ffffff")
        .roundedRect(104, 104, pageWidth - 208, pageHeight - 238, 22)
        .fill()
        .restore();
    }

    doc
      .lineWidth(3)
      .strokeColor("#0b2447")
      .rect(36, 36, pageWidth - 72, pageHeight - 72)
      .stroke();
    doc
      .lineWidth(1)
      .strokeColor("#58c5fb")
      .rect(50, 50, pageWidth - 100, pageHeight - 100)
      .stroke();

    doc
      .font("Times-Bold")
      .fontSize(14)
      .fillColor("#0b2447")
      .text("BALILI ELEMENTARY SCHOOL", 48, 84, {
        align: "center",
        width: pageWidth - 96,
      });
    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#475569")
      .text("ORATRACK Generated Certificate", {
        align: "center",
        width: pageWidth - 96,
      });

    doc.moveDown(1.6);
    doc
      .font("Times-Bold")
      .fontSize(34)
      .fillColor("#071b33")
      .text(title.toUpperCase(), {
        align: "center",
        width: pageWidth - 96,
      });

    doc.moveDown(1.3);
    doc
      .font("Helvetica")
      .fontSize(12)
      .fillColor("#475569")
      .text("This certificate is proudly presented to", {
        align: "center",
        width: pageWidth - 96,
      });

    doc.moveDown(0.35);
    doc
      .font("Times-Bold")
      .fontSize(32)
      .fillColor("#0b2447")
      .text(input.learnerName, {
        align: "center",
        width: pageWidth - 96,
      });

    doc.moveDown(0.5);
    doc
      .font("Helvetica")
      .fontSize(12)
      .fillColor("#475569")
      .text(
        `LRN ${input.lrn} | ${input.gradeLevelLabel} ${input.sectionName} | ${input.schoolYearName}`,
        {
          align: "center",
          width: pageWidth - 96,
        },
      );

    doc.moveDown(1.2);
    doc
      .font("Helvetica")
      .fontSize(13)
      .fillColor("#0f172a")
      .text(
        input.certificateType === "completion"
          ? "For successfully completing the required school records and learning requirements for the selected school year."
          : "For commendable effort, progress, and achievement recorded in the school monitoring system.",
        {
          align: "center",
          lineGap: 4,
          width: pageWidth - 220,
        },
      );

    doc
      .moveTo(150, pageHeight - 130)
      .lineTo(340, pageHeight - 130)
      .strokeColor("#94a3b8")
      .stroke();
    doc
      .moveTo(pageWidth - 340, pageHeight - 130)
      .lineTo(pageWidth - 150, pageHeight - 130)
      .stroke();

    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor("#0b2447")
      .text("Class Adviser", 150, pageHeight - 116, {
        align: "center",
        width: 190,
      });
    doc.text("School Principal", pageWidth - 340, pageHeight - 116, {
      align: "center",
      width: 190,
    });

    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor("#64748b")
      .text(
        `Template: ${input.templateName ?? "Temporary clean template"} | Generated ${new Date(input.generatedAt).toLocaleDateString("en")}`,
        48,
        pageHeight - 66,
        { align: "center", width: pageWidth - 96 },
      );

    doc.end();
  });
}
