import PDFDocument from "pdfkit";

export type PdfReportInput = {
  title: string;
  subtitle: string;
  lines: string[];
};

export function createSimplePdfReport(input: PdfReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).text(input.title, { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#475569").text(input.subtitle);
    doc.moveDown(1.5);
    doc.fillColor("#0f172a").fontSize(11);

    input.lines.forEach((line) => {
      doc.text(line, { lineGap: 5 });
    });

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor("#64748b")
      .text(
        "Generated by ORATRACK. Verify all values before official submission.",
      );
    doc.end();
  });
}
